// File generated by FlutterFire CLI. //
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps. //wist 7-15 ws firebaseOptions, ws DefaultFirebaseOptions
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      //wist
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    //connection app to firebase
    apiKey: 'AIzaSyD8WnUOSDLa2hUPrQW8EHj6tQ7dERx27vc',
    appId: '1:345183958137:android:09938eaf637d27d82ad0a8',
    messagingSenderId: '345183958137',
    projectId: 'read-me-a-story3',
    storageBucket: 'read-me-a-story3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLPkjSndnZdTKn-7AUWAisdvnw-iU9Da0',
    appId: '1:345183958137:ios:563f0701fbace3442ad0a8',
    messagingSenderId: '345183958137',
    projectId: 'read-me-a-story3',
    storageBucket: 'read-me-a-story3.appspot.com',
    iosClientId:
        '345183958137-32238fs8450u75ehr2861a2se9fbra01.apps.googleusercontent.com',
    iosBundleId: 'com.reemaaliii.readMeAStory',
  );
}
